[package]
name = "spawn-camp"
version = "1.0.2"
edition = "2021"

[dependencies]
ringhopper = { git = "https://github.com/FishAndRips/ringhopper" }
vulkano = "0.34.1"
vulkano-shaders = "0.34.0"
clap = "4.5.31"
hex_color = "3.0.0"
